services:
  django:
    image: django:latest
    build:
      context: ..
      dockerfile: oci/Dockerfile
    platform: linux/amd64
    env_file:
      - ../.env
    tty: true
    ports:
      - "8080:8080"
    environment:
      - ENV=production
    volumes:
      - ../src:/app/

  postgres:
    image: postgres:14.20-alpine3.23
    env_file:
      - ../.env